-- Agents Database Schema
-- Single source of truth for agents.db
-- This schema represents the final state after all migrations

-- Sequences table: candidate trade action sequences
-- Generated by planner for evaluation
CREATE TABLE IF NOT EXISTS sequences (
    sequence_hash TEXT NOT NULL,
    portfolio_hash TEXT NOT NULL,
    priority REAL NOT NULL,
    sequence_json TEXT NOT NULL,     -- JSON serialized List[ActionCandidate]
    depth INTEGER NOT NULL,          -- Sequence depth (1-5)
    pattern_type TEXT,               -- Pattern: 'direct_buy', 'combinatorial', etc.
    completed INTEGER DEFAULT 0,     -- 0 = not evaluated, 1 = evaluated
    evaluated_at INTEGER,            -- Unix timestamp when evaluated (seconds since epoch)
    created_at INTEGER NOT NULL,     -- Unix timestamp (seconds since epoch)
    PRIMARY KEY (sequence_hash, portfolio_hash)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_sequences_portfolio ON sequences(portfolio_hash);
CREATE INDEX IF NOT EXISTS idx_sequences_priority ON sequences(portfolio_hash, priority DESC, completed);
CREATE INDEX IF NOT EXISTS idx_sequences_completed ON sequences(portfolio_hash, completed);

-- Evaluations table: evaluation results for sequences
CREATE TABLE IF NOT EXISTS evaluations (
    sequence_hash TEXT NOT NULL,
    portfolio_hash TEXT NOT NULL,
    end_score REAL NOT NULL,
    breakdown_json TEXT NOT NULL,    -- JSON serialized score breakdown
    end_cash REAL NOT NULL,
    end_context_positions_json TEXT NOT NULL,  -- JSON Dict[str, float]
    div_score REAL NOT NULL,         -- Diversification score
    total_value REAL NOT NULL,       -- Total portfolio value after sequence
    evaluated_at INTEGER NOT NULL,   -- Unix timestamp (seconds since epoch)
    PRIMARY KEY (sequence_hash, portfolio_hash)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_evaluations_portfolio ON evaluations(portfolio_hash);
CREATE INDEX IF NOT EXISTS idx_evaluations_score ON evaluations(portfolio_hash, end_score DESC);

-- Best result table: best sequence per portfolio state
CREATE TABLE IF NOT EXISTS best_result (
    portfolio_hash TEXT PRIMARY KEY,
    sequence_hash TEXT NOT NULL,
    plan_data TEXT NOT NULL,         -- JSON serialized HolisticPlan
    score REAL NOT NULL,
    created_at INTEGER NOT NULL,      -- Unix timestamp (seconds since epoch)
    updated_at INTEGER NOT NULL      -- Unix timestamp (seconds since epoch)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_best_result_score ON best_result(score DESC);
