#!/usr/bin/env bash
# Generate version.go with commit timestamp

VERSION="v$(date -u +%Y.%m.%d.%H.%M)"
mkdir -p internal/version

cat > internal/version/version.go <<EOF
// Package version contains the build version information.
package version

// Version is the build version (generated by pre-commit hook)
var Version = "$VERSION"
EOF

git add internal/version/version.go
echo "✓ Generated version: $VERSION"
