-- Cache Database Schema
-- Migration 008: Create cache.db schema for ephemeral operational data
--
-- This migration creates tables for the cache database:
-- - Recommendations: Trade recommendations (short-lived operational data)
-- - Cache data: Temporary/computed data that can be rebuilt
--
-- Characteristics:
-- - NO backups (can be deleted and rebuilt anytime)
-- - ProfileCache settings (synchronous=OFF for maximum speed)
-- - Automatic cleanup of old data
--
-- Data Migration Note:
-- During Phase 6:
-- - Move recommendations from config.db (if exists) → cache.db

-- Recommendations table: trading plan recommendations
-- Generated by PlannerBatchJob, consumed by EventBasedTradingJob
-- Short-lived operational data (cleared after execution or expiration)
CREATE TABLE IF NOT EXISTS recommendations (
    uuid TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('buy', 'sell')),
    quantity REAL NOT NULL CHECK (quantity > 0),
    estimated_price REAL NOT NULL CHECK (estimated_price > 0),
    estimated_value REAL NOT NULL,
    reason TEXT NOT NULL,
    currency TEXT NOT NULL,
    priority REAL NOT NULL,
    current_portfolio_score REAL NOT NULL,
    new_portfolio_score REAL NOT NULL,
    score_change REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'rejected', 'expired')),
    portfolio_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    executed_at TEXT
) STRICT;

CREATE INDEX IF NOT EXISTS idx_recommendations_status_priority
ON recommendations(status, priority ASC, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_recommendations_portfolio_hash
ON recommendations(portfolio_hash, status);

CREATE INDEX IF NOT EXISTS idx_recommendations_executed_at
ON recommendations(executed_at) WHERE executed_at IS NOT NULL;

-- Cache data table: generic key-value cache
-- For temporary computed results that can be rebuilt
CREATE TABLE IF NOT EXISTS cache_data (
    cache_key TEXT PRIMARY KEY,
    cache_value TEXT NOT NULL,       -- JSON or serialized data
    expires_at INTEGER,              -- Unix timestamp (NULL = never expires)
    created_at INTEGER NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_cache_expires ON cache_data(expires_at);

-- Database health tracking table
CREATE TABLE IF NOT EXISTS _database_health (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    checked_at INTEGER NOT NULL,  -- Unix timestamp
    integrity_check_passed INTEGER NOT NULL,  -- Boolean: 1 = passed, 0 = failed
    size_bytes INTEGER NOT NULL,
    wal_size_bytes INTEGER,
    page_count INTEGER,
    freelist_count INTEGER,
    vacuum_performed INTEGER DEFAULT 0,  -- Boolean: 1 = yes, 0 = no
    notes TEXT
) STRICT;

CREATE INDEX IF NOT EXISTS idx_health_checked_at ON _database_health(checked_at);
