/**
 * Next Actions View
 * 
 * Main view for displaying and executing trading recommendations.
 * Shows recommended actions (buy/sell) generated by the planner.
 * 
 * Features:
 * - Trading recommendations display (via NextActionsCard)
 * - Planner configuration button
 * - Research mode controls (cooloff period toggle for testing)
 * 
 * This is the primary view for reviewing and executing trading decisions.
 */
import { Group, Button, Stack, Switch, Text, Tooltip } from '@mantine/core';
import { NextActionsCard } from '../components/portfolio/NextActionsCard';
import { useAppStore } from '../stores/appStore';
import { useSettingsStore } from '../stores/settingsStore';

/**
 * Next Actions view component
 * 
 * Displays trading recommendations and provides controls for planner configuration
 * and research mode testing options.
 * 
 * @returns {JSX.Element} Next Actions view with recommendations and controls
 */
export function NextActions() {
  const { openPlannerManagementModal } = useAppStore();
  const { settings, tradingMode, updateSetting } = useSettingsStore();

  // Check if in research mode (paper trading)
  const isResearchMode = tradingMode === 'research';
  // Check if cooloff checks are disabled (for testing)
  const isCooloffDisabled = settings.disable_cooloff_checks >= 1.0;

  /**
   * Handles toggling the cooloff period checks
   * 
   * Only available in research mode. Disables the cooloff period
   * that normally prevents rapid-fire trades for testing purposes.
   * 
   * @param {Event} event - Change event from the switch
   */
  const handleCooloffToggle = async (event) => {
    const newValue = event.currentTarget.checked ? 1.0 : 0.0;
    try {
      await updateSetting('disable_cooloff_checks', newValue);
    } catch (error) {
      console.error('Failed to toggle cooloff checks:', error);
    }
  };

  return (
    <Stack className="next-actions-view" gap="md">
      {/* Action controls bar */}
      <Group className="next-actions-view__actions" justify="space-between" wrap="wrap">
        {/* Research mode testing controls - only shown in research mode */}
        {isResearchMode && (
          <Tooltip label="Disable cooloff period checks for testing (only works in research mode)">
            <Group className="next-actions-view__cooloff-toggle" gap="xs">
              <Switch
                className="next-actions-view__cooloff-switch"
                checked={isCooloffDisabled}
                onChange={handleCooloffToggle}
                size="sm"
                color="orange"
              />
              <Text className="next-actions-view__cooloff-label" size="sm" c="dimmed">Disable Cooloff</Text>
            </Group>
          </Tooltip>
        )}

        {/* Spacer when not in research mode to push button to the right */}
        {!isResearchMode && <div className="next-actions-view__spacer" />}

        {/* Planner configuration button */}
        <Button
          className="next-actions-view__configure-btn"
          variant="light"
          color="green"
          size="sm"
          onClick={() => openPlannerManagementModal()}
        >
          ⚙️ Configure Planner
        </Button>
      </Group>

      {/* Main recommendations card */}
      <NextActionsCard />
    </Stack>
  );
}
